//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kurs4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Выгр файла.
    /// </summary>
    // *** Start programmer edit section *** (ВыгрФайла CustomAttributes)

    // *** End programmer edit section *** (ВыгрФайла CustomAttributes)
    [AutoAltered()]
    [Caption("Выгрузка файла")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВыгрФайлаE", new string[] {
            "NewName as \'Новое имя файла\'",
            "Репозиторий as \'Репозиторий\'",
            "Конвертация as \'Имя документа\'",
            "Конвертация.ИмяДок as \'Имя документа\'"}, Hidden=new string[] {
            "Конвертация.ИмяДок"})]
    [MasterViewDefineAttribute("ВыгрФайлаE", "Конвертация", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ИмяДок")]
    [View("ВыгрФайлаL", new string[] {
            "NewName as \'Новое имя файла\'",
            "Репозиторий as \'Репозиторий\'",
            "Конвертация.ИмяДок as \'Имя документа\'"})]
    public class ВыгрФайла : ICSSoft.STORMNET.DataObject
    {
        
        private string fNewName;
        
        private string fРепозиторий;
        
        private IIS.Kurs4.Конвертация fКонвертация;
        
        // *** Start programmer edit section *** (ВыгрФайла CustomMembers)

        // *** End programmer edit section *** (ВыгрФайла CustomMembers)

        
        /// <summary>
        /// NewName.
        /// </summary>
        // *** Start programmer edit section *** (ВыгрФайла.NewName CustomAttributes)

        // *** End programmer edit section *** (ВыгрФайла.NewName CustomAttributes)
        [StrLen(255)]
        public virtual string NewName
        {
            get
            {
                // *** Start programmer edit section *** (ВыгрФайла.NewName Get start)

                // *** End programmer edit section *** (ВыгрФайла.NewName Get start)
                string result = this.fNewName;
                // *** Start programmer edit section *** (ВыгрФайла.NewName Get end)

                // *** End programmer edit section *** (ВыгрФайла.NewName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВыгрФайла.NewName Set start)

                // *** End programmer edit section *** (ВыгрФайла.NewName Set start)
                this.fNewName = value;
                // *** Start programmer edit section *** (ВыгрФайла.NewName Set end)

                // *** End programmer edit section *** (ВыгрФайла.NewName Set end)
            }
        }
        
        /// <summary>
        /// Репозиторий.
        /// </summary>
        // *** Start programmer edit section *** (ВыгрФайла.Репозиторий CustomAttributes)

        // *** End programmer edit section *** (ВыгрФайла.Репозиторий CustomAttributes)
        [StrLen(255)]
        public virtual string Репозиторий
        {
            get
            {
                // *** Start programmer edit section *** (ВыгрФайла.Репозиторий Get start)

                // *** End programmer edit section *** (ВыгрФайла.Репозиторий Get start)
                string result = this.fРепозиторий;
                // *** Start programmer edit section *** (ВыгрФайла.Репозиторий Get end)

                // *** End programmer edit section *** (ВыгрФайла.Репозиторий Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВыгрФайла.Репозиторий Set start)

                // *** End programmer edit section *** (ВыгрФайла.Репозиторий Set start)
                this.fРепозиторий = value;
                // *** Start programmer edit section *** (ВыгрФайла.Репозиторий Set end)

                // *** End programmer edit section *** (ВыгрФайла.Репозиторий Set end)
            }
        }
        
        /// <summary>
        /// Выгр файла.
        /// </summary>
        // *** Start programmer edit section *** (ВыгрФайла.Конвертация CustomAttributes)

        // *** End programmer edit section *** (ВыгрФайла.Конвертация CustomAttributes)
        [PropertyStorage(new string[] {
                "Конвертация"})]
        [NotNull()]
        public virtual IIS.Kurs4.Конвертация Конвертация
        {
            get
            {
                // *** Start programmer edit section *** (ВыгрФайла.Конвертация Get start)

                // *** End programmer edit section *** (ВыгрФайла.Конвертация Get start)
                IIS.Kurs4.Конвертация result = this.fКонвертация;
                // *** Start programmer edit section *** (ВыгрФайла.Конвертация Get end)

                // *** End programmer edit section *** (ВыгрФайла.Конвертация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВыгрФайла.Конвертация Set start)

                // *** End programmer edit section *** (ВыгрФайла.Конвертация Set start)
                this.fКонвертация = value;
                // *** Start programmer edit section *** (ВыгрФайла.Конвертация Set end)

                // *** End programmer edit section *** (ВыгрФайла.Конвертация Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВыгрФайлаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВыгрФайлаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВыгрФайлаE", typeof(IIS.Kurs4.ВыгрФайла));
                }
            }
            
            /// <summary>
            /// "ВыгрФайлаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВыгрФайлаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВыгрФайлаL", typeof(IIS.Kurs4.ВыгрФайла));
                }
            }
        }
    }
}
