//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kurs4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Загр файла.
    /// </summary>
    // *** Start programmer edit section *** (ЗагрФайла CustomAttributes)

    // *** End programmer edit section *** (ЗагрФайла CustomAttributes)
    [AutoAltered()]
    [Caption("Загрузка файла")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗагрФайлаE", new string[] {
            "Дата as \'Дата\'",
            "Путь as \'Путь\'",
            "ЭксФайлы as \'Эксель файл\'",
            "ЭксФайлы.Репозиторий as \'Репозиторий\'",
            "ЭксФайлы.Имя as \'Имя\'"}, Hidden=new string[] {
            "ЭксФайлы.Репозиторий"})]
    [AssociatedDetailViewAttribute("ЗагрФайлаE", "Тч_загр", "Тч_загрE", true, "", "Атрибуты загрузки", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЗагрФайлаE", "ЭксФайлы", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Репозиторий")]
    [View("ЗагрФайлаL", new string[] {
            "Дата as \'Дата\'",
            "Путь as \'Путь\'",
            "ЭксФайлы.Имя as \'Имя\'"})]
    public class ЗагрФайла : ICSSoft.STORMNET.DataObject
    {
        
        private string fПуть;
        
        private System.DateTime fДата;
        
        private IIS.Kurs4.ЭксФайлы fЭксФайлы;
        
        private IIS.Kurs4.DetailArrayOfТч_загр fТч_загр;
        
        // *** Start programmer edit section *** (ЗагрФайла CustomMembers)

        // *** End programmer edit section *** (ЗагрФайла CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ЗагрФайла.Дата CustomAttributes)

        // *** End programmer edit section *** (ЗагрФайла.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ЗагрФайла.Дата Get start)

                // *** End programmer edit section *** (ЗагрФайла.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ЗагрФайла.Дата Get end)

                // *** End programmer edit section *** (ЗагрФайла.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗагрФайла.Дата Set start)

                // *** End programmer edit section *** (ЗагрФайла.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ЗагрФайла.Дата Set end)

                // *** End programmer edit section *** (ЗагрФайла.Дата Set end)
            }
        }
        
        /// <summary>
        /// Путь.
        /// </summary>
        // *** Start programmer edit section *** (ЗагрФайла.Путь CustomAttributes)

        // *** End programmer edit section *** (ЗагрФайла.Путь CustomAttributes)
        [StrLen(255)]
        public virtual string Путь
        {
            get
            {
                // *** Start programmer edit section *** (ЗагрФайла.Путь Get start)

                // *** End programmer edit section *** (ЗагрФайла.Путь Get start)
                string result = this.fПуть;
                // *** Start programmer edit section *** (ЗагрФайла.Путь Get end)

                // *** End programmer edit section *** (ЗагрФайла.Путь Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗагрФайла.Путь Set start)

                // *** End programmer edit section *** (ЗагрФайла.Путь Set start)
                this.fПуть = value;
                // *** Start programmer edit section *** (ЗагрФайла.Путь Set end)

                // *** End programmer edit section *** (ЗагрФайла.Путь Set end)
            }
        }
        
        /// <summary>
        /// Загр файла.
        /// </summary>
        // *** Start programmer edit section *** (ЗагрФайла.ЭксФайлы CustomAttributes)

        // *** End programmer edit section *** (ЗагрФайла.ЭксФайлы CustomAttributes)
        [PropertyStorage(new string[] {
                "ЭксФайлы"})]
        [NotNull()]
        public virtual IIS.Kurs4.ЭксФайлы ЭксФайлы
        {
            get
            {
                // *** Start programmer edit section *** (ЗагрФайла.ЭксФайлы Get start)

                // *** End programmer edit section *** (ЗагрФайла.ЭксФайлы Get start)
                IIS.Kurs4.ЭксФайлы result = this.fЭксФайлы;
                // *** Start programmer edit section *** (ЗагрФайла.ЭксФайлы Get end)

                // *** End programmer edit section *** (ЗагрФайла.ЭксФайлы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗагрФайла.ЭксФайлы Set start)

                // *** End programmer edit section *** (ЗагрФайла.ЭксФайлы Set start)
                this.fЭксФайлы = value;
                // *** Start programmer edit section *** (ЗагрФайла.ЭксФайлы Set end)

                // *** End programmer edit section *** (ЗагрФайла.ЭксФайлы Set end)
            }
        }
        
        /// <summary>
        /// Загр файла.
        /// </summary>
        // *** Start programmer edit section *** (ЗагрФайла.Тч_загр CustomAttributes)

        // *** End programmer edit section *** (ЗагрФайла.Тч_загр CustomAttributes)
        public virtual IIS.Kurs4.DetailArrayOfТч_загр Тч_загр
        {
            get
            {
                // *** Start programmer edit section *** (ЗагрФайла.Тч_загр Get start)

                // *** End programmer edit section *** (ЗагрФайла.Тч_загр Get start)
                if ((this.fТч_загр == null))
                {
                    this.fТч_загр = new IIS.Kurs4.DetailArrayOfТч_загр(this);
                }
                IIS.Kurs4.DetailArrayOfТч_загр result = this.fТч_загр;
                // *** Start programmer edit section *** (ЗагрФайла.Тч_загр Get end)

                // *** End programmer edit section *** (ЗагрФайла.Тч_загр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗагрФайла.Тч_загр Set start)

                // *** End programmer edit section *** (ЗагрФайла.Тч_загр Set start)
                this.fТч_загр = value;
                // *** Start programmer edit section *** (ЗагрФайла.Тч_загр Set end)

                // *** End programmer edit section *** (ЗагрФайла.Тч_загр Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗагрФайлаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗагрФайлаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗагрФайлаE", typeof(IIS.Kurs4.ЗагрФайла));
                }
            }
            
            /// <summary>
            /// "ЗагрФайлаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗагрФайлаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗагрФайлаL", typeof(IIS.Kurs4.ЗагрФайла));
                }
            }
        }
    }
}
