//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kurs4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Настр конв.
    /// </summary>
    // *** Start programmer edit section *** (НастрКонв CustomAttributes)

    // *** End programmer edit section *** (НастрКонв CustomAttributes)
    [AutoAltered()]
    [Caption("Настройки конвертации")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НастрКонвE", new string[] {
            "Наименование as \'Наименование\'"})]
    [AssociatedDetailViewAttribute("НастрКонвE", "Тч_настр", "Тч_настрE", true, "", "Атрибуты настройки", true, new string[] {
            ""})]
    [View("НастрКонвL", new string[] {
            "Наименование as \'Наименование\'"})]
    public class НастрКонв : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private IIS.Kurs4.DetailArrayOfТч_настр fТч_настр;
        
        // *** Start programmer edit section *** (НастрКонв CustomMembers)

        // *** End programmer edit section *** (НастрКонв CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (НастрКонв.Наименование CustomAttributes)

        // *** End programmer edit section *** (НастрКонв.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (НастрКонв.Наименование Get start)

                // *** End programmer edit section *** (НастрКонв.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (НастрКонв.Наименование Get end)

                // *** End programmer edit section *** (НастрКонв.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (НастрКонв.Наименование Set start)

                // *** End programmer edit section *** (НастрКонв.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (НастрКонв.Наименование Set end)

                // *** End programmer edit section *** (НастрКонв.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Настр конв.
        /// </summary>
        // *** Start programmer edit section *** (НастрКонв.Тч_настр CustomAttributes)

        // *** End programmer edit section *** (НастрКонв.Тч_настр CustomAttributes)
        public virtual IIS.Kurs4.DetailArrayOfТч_настр Тч_настр
        {
            get
            {
                // *** Start programmer edit section *** (НастрКонв.Тч_настр Get start)

                // *** End programmer edit section *** (НастрКонв.Тч_настр Get start)
                if ((this.fТч_настр == null))
                {
                    this.fТч_настр = new IIS.Kurs4.DetailArrayOfТч_настр(this);
                }
                IIS.Kurs4.DetailArrayOfТч_настр result = this.fТч_настр;
                // *** Start programmer edit section *** (НастрКонв.Тч_настр Get end)

                // *** End programmer edit section *** (НастрКонв.Тч_настр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (НастрКонв.Тч_настр Set start)

                // *** End programmer edit section *** (НастрКонв.Тч_настр Set start)
                this.fТч_настр = value;
                // *** Start programmer edit section *** (НастрКонв.Тч_настр Set end)

                // *** End programmer edit section *** (НастрКонв.Тч_настр Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НастрКонвE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НастрКонвE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НастрКонвE", typeof(IIS.Kurs4.НастрКонв));
                }
            }
            
            /// <summary>
            /// "НастрКонвL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НастрКонвL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НастрКонвL", typeof(IIS.Kurs4.НастрКонв));
                }
            }
        }
    }
}
