//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kurs4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тч_загр.
    /// </summary>
    // *** Start programmer edit section *** (Тч_загр CustomAttributes)

    // *** End programmer edit section *** (Тч_загр CustomAttributes)
    [AutoAltered()]
    [Caption("Атрибуты загрузки")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Тч_загрE", new string[] {
            "Атрибут as \'Атрибут\'",
            "Ограничение as \'Ограничение\'",
            "Обязательный as \'Обязательный\'",
            "ТипАтр as \'Тип атр\'"})]
    public class Тч_загр : ICSSoft.STORMNET.DataObject
    {
        
        private string fАтрибут;
        
        private int fОграничение;
        
        private bool fОбязательный;
        
        private IIS.Kurs4.ТипАтр fТипАтр;
        
        private IIS.Kurs4.ЗагрФайла fЗагрФайла;
        
        // *** Start programmer edit section *** (Тч_загр CustomMembers)

        // *** End programmer edit section *** (Тч_загр CustomMembers)

        
        /// <summary>
        /// Атрибут.
        /// </summary>
        // *** Start programmer edit section *** (Тч_загр.Атрибут CustomAttributes)

        // *** End programmer edit section *** (Тч_загр.Атрибут CustomAttributes)
        [StrLen(255)]
        public virtual string Атрибут
        {
            get
            {
                // *** Start programmer edit section *** (Тч_загр.Атрибут Get start)

                // *** End programmer edit section *** (Тч_загр.Атрибут Get start)
                string result = this.fАтрибут;
                // *** Start programmer edit section *** (Тч_загр.Атрибут Get end)

                // *** End programmer edit section *** (Тч_загр.Атрибут Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч_загр.Атрибут Set start)

                // *** End programmer edit section *** (Тч_загр.Атрибут Set start)
                this.fАтрибут = value;
                // *** Start programmer edit section *** (Тч_загр.Атрибут Set end)

                // *** End programmer edit section *** (Тч_загр.Атрибут Set end)
            }
        }
        
        /// <summary>
        /// Обязательный.
        /// </summary>
        // *** Start programmer edit section *** (Тч_загр.Обязательный CustomAttributes)

        // *** End programmer edit section *** (Тч_загр.Обязательный CustomAttributes)
        public virtual bool Обязательный
        {
            get
            {
                // *** Start programmer edit section *** (Тч_загр.Обязательный Get start)

                // *** End programmer edit section *** (Тч_загр.Обязательный Get start)
                bool result = this.fОбязательный;
                // *** Start programmer edit section *** (Тч_загр.Обязательный Get end)

                // *** End programmer edit section *** (Тч_загр.Обязательный Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч_загр.Обязательный Set start)

                // *** End programmer edit section *** (Тч_загр.Обязательный Set start)
                this.fОбязательный = value;
                // *** Start programmer edit section *** (Тч_загр.Обязательный Set end)

                // *** End programmer edit section *** (Тч_загр.Обязательный Set end)
            }
        }
        
        /// <summary>
        /// Ограничение.
        /// </summary>
        // *** Start programmer edit section *** (Тч_загр.Ограничение CustomAttributes)

        // *** End programmer edit section *** (Тч_загр.Ограничение CustomAttributes)
        public virtual int Ограничение
        {
            get
            {
                // *** Start programmer edit section *** (Тч_загр.Ограничение Get start)

                // *** End programmer edit section *** (Тч_загр.Ограничение Get start)
                int result = this.fОграничение;
                // *** Start programmer edit section *** (Тч_загр.Ограничение Get end)

                // *** End programmer edit section *** (Тч_загр.Ограничение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч_загр.Ограничение Set start)

                // *** End programmer edit section *** (Тч_загр.Ограничение Set start)
                this.fОграничение = value;
                // *** Start programmer edit section *** (Тч_загр.Ограничение Set end)

                // *** End programmer edit section *** (Тч_загр.Ограничение Set end)
            }
        }
        
        /// <summary>
        /// ТипАтр.
        /// </summary>
        // *** Start programmer edit section *** (Тч_загр.ТипАтр CustomAttributes)

        // *** End programmer edit section *** (Тч_загр.ТипАтр CustomAttributes)
        public virtual IIS.Kurs4.ТипАтр ТипАтр
        {
            get
            {
                // *** Start programmer edit section *** (Тч_загр.ТипАтр Get start)

                // *** End programmer edit section *** (Тч_загр.ТипАтр Get start)
                IIS.Kurs4.ТипАтр result = this.fТипАтр;
                // *** Start programmer edit section *** (Тч_загр.ТипАтр Get end)

                // *** End programmer edit section *** (Тч_загр.ТипАтр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч_загр.ТипАтр Set start)

                // *** End programmer edit section *** (Тч_загр.ТипАтр Set start)
                this.fТипАтр = value;
                // *** Start programmer edit section *** (Тч_загр.ТипАтр Set end)

                // *** End programmer edit section *** (Тч_загр.ТипАтр Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Kurs4.ЗагрФайла.
        /// </summary>
        // *** Start programmer edit section *** (Тч_загр.ЗагрФайла CustomAttributes)

        // *** End programmer edit section *** (Тч_загр.ЗагрФайла CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ЗагрФайла"})]
        public virtual IIS.Kurs4.ЗагрФайла ЗагрФайла
        {
            get
            {
                // *** Start programmer edit section *** (Тч_загр.ЗагрФайла Get start)

                // *** End programmer edit section *** (Тч_загр.ЗагрФайла Get start)
                IIS.Kurs4.ЗагрФайла result = this.fЗагрФайла;
                // *** Start programmer edit section *** (Тч_загр.ЗагрФайла Get end)

                // *** End programmer edit section *** (Тч_загр.ЗагрФайла Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч_загр.ЗагрФайла Set start)

                // *** End programmer edit section *** (Тч_загр.ЗагрФайла Set start)
                this.fЗагрФайла = value;
                // *** Start programmer edit section *** (Тч_загр.ЗагрФайла Set end)

                // *** End programmer edit section *** (Тч_загр.ЗагрФайла Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Тч_загрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Тч_загрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Тч_загрE", typeof(IIS.Kurs4.Тч_загр));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Тч_загр.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТч_загр CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТч_загр CustomAttributes)
    public class DetailArrayOfТч_загр : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Kurs4.DetailArrayOfТч_загр members)

        // *** End programmer edit section *** (IIS.Kurs4.DetailArrayOfТч_загр members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Тч_загр by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Тч_загр.
        /// </summary>
        public DetailArrayOfТч_загр(IIS.Kurs4.ЗагрФайла fЗагрФайла) : 
                base(typeof(Тч_загр), ((ICSSoft.STORMNET.DataObject)(fЗагрФайла)))
        {
        }
        
        public IIS.Kurs4.Тч_загр this[int index]
        {
            get
            {
                return ((IIS.Kurs4.Тч_загр)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Kurs4.Тч_загр dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
